shadowsocks/shadowsocks-windows

shadowsocks-csharp/View/MenuViewController.cs
"configForm.Focus()" can't bring the form to front  when the form have been opened and back of some other windows. The solution is use "configForm.Activate()".
=> Bring config form to front when it's opened before.

shadowsocks-csharp/Controller/System/SystemProxy.cs
在公司内部有部署WPAD代理自动发现时，必须禁用“自动检测设置”，指定的PAC才会生效。否则会优先使用wpad.dat的规则文件。
另外，IE原来设置了个人的（或公司内部的）代理服务器，如果临时用下SS的PAC，没必须把代理服务器也清除。这样在取消SS的启用系统代理之后，不需要再重新填写一遍个人代理地址和端口。
=> 启用系统代理时禁用“自动检测设置”，并且无必要时不清除原有代理服务器设置。

shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Controller/Strategy/SimplyChooseByStatisticsStrategy.cs, shadowsocks-csharp/Controller/Strategy/StrategyManager.cs, shadowsocks-csharp/Data/cn.txt, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/shadowsocks-csharp.csproj
Strategy: Simply Choose By Statistics
启用该选项后后台定时（目前是60分钟，似乎应该调小一些）利用 .Net [原生接口](https://msdn.microsoft.com/en-us/library/System.Net.NetworkInformation(v=vs.110).aspx)收集到所有代理的ICMP数据，然后记录在文件里。（可能的改进是对于 Strategy 默认提供的 LastRead，LastWrite 等事件也记录下来）
可以用于统计分析，比如基于时间段，在晚间（中美线路高峰），代理1的表现可能比代理2更好，白天则代理2更好。等等。
Strategy 可以读取文件自行设计算法，我已经写了一个简单的（选择历史总丢包率最小的）。除了ReloadServers事件以外，每隔60分钟根据数据计算一次然后选择。
=> Add availability statistics service and a simple strategy

shadowsocks-csharp/View/ConfigForm.cs
Sometimes the users may hit enter key by mistake, and the form will
close without saving entries.
有时在设置代理时，若不慎按下回车，窗口会关闭而且设置内容不会保存。
该commit修复了这个问题，当回车键按下后，会保存设置。
=> Fix a tiny bug

shadowsocks-csharp/Encryption/IVEncryptor.cs
Part of pull request #313 
>The stock code use class Random to generate IV, the Random is pseudo random number generator. The IV maybe repeat, this will cause shadowsocks-libev closed the sockets with the error message 'invalid password or cipher'. Reference https://github.com/shadowsocks/shadowsocks-libev/issues/389
>Solution is use class RNGCryptoServiceProvider to generate IV, of course it's lower performance, but a little bit.
=> no repeat random number generator by GangZhuo

CHANGES, shadowsocks-csharp/Controller/Service/UpdateChecker.cs, shadowsocks-csharp/Model/StatisticsStrategyConfiguration.cs, shadowsocks-csharp/Properties/AssemblyInfo.cs
As the StatisticsStrategy is not stable, it should be disable by default.
=> Disable StatisticsStrategy by default.

shadowsocks-csharp/View/LogForm.cs
This exception is caused by processing Invoke Action while trafficChart is already disposed.
=====
Exception reproduce frequency: RARE. Once triggered, ShadowSocks crashes.
=> Fix the System.ObjectDisposedException when closing the LogForm

shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Util/Util.cs
- featured print "connect to hostname:port" to log
- renamed private properties with prefix underline
- clean up code in C# 6
- clean up buggy parameter.
- Replaced SocketFlags.None (an enum which euqals 0) from zero.
=> New Feature: print "connect to hostname:port" to log

shadowsocks-csharp/Controller/Service/PortForwarder.cs, shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/Service/UDPRelay.cs, shadowsocks-csharp/Data/cn.txt, shadowsocks-csharp/Proxy/DirectConnect.cs, shadowsocks-csharp/Proxy/IProxy.cs, shadowsocks-csharp/Proxy/Socks5Proxy.cs, shadowsocks-csharp/Util/SocketUtil.cs, shadowsocks-csharp/shadowsocks-csharp.csproj
When using ss through another socks5 proxy, the prev version still resolves ss server's domain name locally. This could lead to wrong results.
This patch allow proxy module to resolve domain name itself.
-Socks5 proxy: just pass the domain name to socks5 proxy server cuz the protocol support domain name.
-Direct connect: still resolves locally and synchronously.
=> Resolving domain name through socks5 proxy

shadowsocks-csharp/Controller/Service/Listener.cs, shadowsocks-csharp/Controller/Service/PolipoRunner.cs, shadowsocks-csharp/Controller/Service/PortForwarder.cs, shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/Service/UDPRelay.cs, shadowsocks-csharp/Proxy/DirectConnect.cs, shadowsocks-csharp/Proxy/Socks5Proxy.cs, shadowsocks-csharp/Util/SocketUtil.cs, shadowsocks-csharp/app.manifest
Only parse socks5 header once per connection.
To avoid unreadable and uncessary output like this:
=> Minor bug fix and improvements.

shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs, shadowsocks-csharp/Controller/Service/Listener.cs, shadowsocks-csharp/Controller/Service/PACServer.cs, shadowsocks-csharp/Controller/Service/PortForwarder.cs, shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/Service/UDPRelay.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/View/LogForm.cs
Use lock to sync between threads.This should fix issue #679 
and other same issue.
Fix a bug in UpdateSpeed() that only save the first xxxSpeedRecord.
This bug was introduced in commit 2aa0620
=> New approach to record and calculate inbound/outbound speed.

shadowsocks-csharp/Encryption/EncryptorBase.cs, shadowsocks-csharp/Encryption/IVEncryptor.cs, shadowsocks-csharp/Encryption/MbedTLSEncryptor.cs, shadowsocks-csharp/Encryption/SodiumEncryptor.cs
- `EncryptorInfo` struct instead of `Dictionary<string, int[]>>`
- <del>Remove useless debug info (also it cost too much time to refresh)</del>
=> Refine Encryption module

README.md
fix: 之前括号中的 `maintained by 3rd party` 覆盖掉了最后GFWList的定义
=> README中的GFWList的链接

shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Util/Util.cs, shadowsocks-csharp/View/LogForm.cs, shadowsocks-csharp/View/MenuViewController.cs
- Rename variable 'traffic' to 'trafficPerSecondQueue' and 'trafficInfoQueue'
- Remove class QueueLast<T> by using linq Queue.Last()
- Slight changes, such as rename, move several variables from function domain to class domain to improve performance. Logic remains the same.
- Update the logic of copying queue from Controller to View.
=> Chart Refactor

shadowsocks-csharp/Controller/Service/Sip003Plugin.cs, shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Model/Server.cs, shadowsocks-csharp/Proxy/Sip003Plugin.cs, shadowsocks-csharp/View/ConfigForm.Designer.cs, shadowsocks-csharp/View/ConfigForm.cs, shadowsocks-csharp/shadowsocks-csharp.csproj, test/UnitTest.cs
Hello,
This is a first draft WIP to get feedback on my approach. This pull request implements SIP002 url (parsing and generation for QR code with backward-compatibility of accepting old-style urls and generating old-style urls when there is no plugin for the config), and SIP003 plugin interface for shadowsocks-windows.
- SIP002 has unit tests and proven to work.
- SIP003 needs a little bit of testing, would appreciate feedback on the approach and fresh eyes to see if I made any mistakes.
Hope to eventually get this merged soon :-)
=> SIP002 and SIP003 support.

shadowsocks-csharp/Controller/Service/Sip003Plugin.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs
This is a follow up to #1298. Uses windows job objects with SIP003 processes so that if shadowsocks is killed SIP003 plugin is killed by OS also (instead of lingering processes).
Hoping for a swift review and merge :-)
=> Use job objects with SIP003 plugin to avoid lingering processes if app is killed

shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Model/Server.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/View/QRCodeForm.cs, test/UnitTest.cs
- Bring back the legacy parser
Needs the legacy Regex pattern to match the legacy standard.
- Refine SIP002 logic
Do not parse the URL userinfo part (`method:password`) by standard .Net URL parser directly because it may contain illegal URL characters.
=> Sip002 refine

shadowsocks-csharp/Controller/ShadowsocksController.cs
解决使用SIP003插件时出现的“端口已被占用”问题 #1615 
初步判断是因为先关掉插件导致Reload时Socket无法立刻关闭
手动测试问题已解决，不知道如何进一步测试，待进一步确认
=> Close sockets before stop plugins

shadowsocks-csharp/app.config
just uncomment the specific node in app.config, no need to recompile
to take effect. It will be shipped as Shadowsocks.exe.config after built.
This is for debugging only.
=> add official way to dump network tracing info

shadowsocks-csharp/View/QRCodeSplashForm.cs
#1768 
VS窗体设计器无法处理位于同一个文件中的两个Form派生类，引起花式报错，造成了一定的困惑。将PerPixelAlphaForm类代码合并进QRCodeSplashForm类即可。
Move PerPixelAlphaForm's code into QRCodeSplashForm to avoid 2 derived class of Form in same file.
Before: QRCodeSplashForm -> PerPixelAlphaForm -> Form
After: QRCodeSplashForm -> Form
=> [Fix] QRCodeSplashForm.cs无法在窗体设计工具中打开

shadowsocks-csharp/Controller/Service/Sip003Plugin.cs
---
Cause: process's additional environment variables are not expanded correctly when processing ProcessStartInfo.Arguments.
Innovated by studentmain (StudentEx <scncgz@gmail.com>)
=> Fix #1969 #1818

shadowsocks-csharp/Util/Sockets/SocketUtil.cs
---
Removed redundant method call.
=> Socket.Close calls Socket.Dispose internally

shadowsocks-csharp/Controller/Logging.cs, shadowsocks-csharp/Controller/System/SystemProxy.cs, shadowsocks-csharp/Data/ja.txt, shadowsocks-csharp/Data/zh_CN.txt, shadowsocks-csharp/Data/zh_TW.txt, shadowsocks-csharp/Util/SystemProxy/ProxyException.cs, shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs
---
#1487
https://github.com/shadowsocks/shadowsocks-windows/issues/1991#issuecomment-422240535
#2013
- Sysproxy.exe sometimes output in UTF16LE, cause parse fail. Manually convert it and retry.
- when fail, log information (`sysproxy` args, `sysproxy query` return string), then clear proxy setting and …
=> Improve sysproxy exception handling

shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs
---
PR for #2022 #2003 , merge user bypass list with LAN IP bypass list. So we can keep user bypass setting without change in GUI or configuration file.
=> Keep user bypass setting when use global proxy mode

shadowsocks-csharp/Controller/System/AutoStartup.cs
---
Marked ApplicationRestartFlags with Flags attribute because enum are powered of 2. The nature of this enum is a set of binary flags.
=> Marked ApplicationRestartFlags with Flags attribute

shadowsocks-csharp/View/ProxyForm.cs
---
Fixed condition for useProxy. "==" instead od "=".
=> Fixed condition for useProxy

shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Data/ja.txt, shadowsocks-csharp/Data/zh_CN.txt, shadowsocks-csharp/Data/zh_TW.txt, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/Model/ProxyConfig.cs, shadowsocks-csharp/Proxy/DirectConnect.cs, shadowsocks-csharp/Proxy/HttpProxy.cs, shadowsocks-csharp/Proxy/IProxy.cs, shadowsocks-csharp/Proxy/Socks5Proxy.cs, shadowsocks-csharp/View/ProxyForm.Designer.cs, shadowsocks-csharp/View/ProxyForm.cs
---
Ported from `对正向HTTP代理添加基本认证功能` #1214
Great thanks to @rickryo
* Add "basic access authentication" support for HTTP proxy
=> add "basic access authentication" support for http proxy

shadowsocks-csharp/Model/Server.cs
---
Hello
At first when getting a key value from `NameValueCollection` the URL will be decoded automatically. So there is no need of `HttpUtility.UrlDecode`.
Secondly, try to parse this `ss://` URL with `Import URL From Clipboard`:
```
ss://cmM0LW1kNTpQRzh2OXpHMFJiVkJDQnpm@1.1.1.1:443?plugin=ck-client%3bUID%3dIprWshnjXx3mS3wnWsIFfcvgcvwt4%2bFcoN7%2bIBZA8nU%5c%3d%3bPublicKey%3dD9baLw4qzRhqUDWyyYvuGBTWUP5Tr0NywoB5%2bkbRtWU%5c%3d%3bServerName%3dbing.com%3bTicketTimeHint%3d3600%3bMaskBrowser%3dchrome%3bNumConn%3d4
```
If you go to shadowsocks server's …
=> Fixed a bug with + in query

shadowsocks-csharp/Controller/Service/UDPRelay.cs
---
Each udp packet sent to UDPHandler fires a new `Receive` loop, which is not expected. There should only be one `Receive` loop in one UDPHandler.
For me, this fixes connection constantly lost when playing _League of Legends_.
=> Fix udp relay

appveyor.yml, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Data/ja.txt, shadowsocks-csharp/Data/zh_CN.txt, shadowsocks-csharp/Data/zh_TW.txt, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/View/ConfigForm.cs, shadowsocks-csharp/View/MenuViewController.cs
---
Fix #1907 
Still need further testing.
😀
=> Refactoring Config Form

shadowsocks-csharp/app.manifest
---
This is the first fix for #2426, also the quickest and dirtiest as the UI will become blurry in the secondary display.
Basically it reverts a change: https://github.com/shadowsocks/shadowsocks-windows/commit/1e072e5f917e65d8ba1251848748d814894b4c2c#diff-dc2430a5071a2f8e51b6cd9abc1adc5bL13
To test you may try: https://github.com/prasethu/RemoteDesktopEmulator
=> Turn off per-monitor DPI awareness as it is not supported

shadowsocks-csharp/Controller/Service/Listener.cs, shadowsocks-csharp/Controller/Service/PACServer.cs, shadowsocks-csharp/Controller/Service/PortForwarder.cs, shadowsocks-csharp/Controller/Service/PrivoxyRunner.cs, shadowsocks-csharp/Controller/Service/UDPRelay.cs, shadowsocks-csharp/Controller/Service/UpdateChecker.cs, shadowsocks-csharp/Controller/System/SystemProxy.cs, shadowsocks-csharp/Data/privoxy_conf.txt, shadowsocks-csharp/Model/Configuration.cs
---
增加IPv6 本地监听功能【纯IPv6，启用后不再监听IPv4】
* 如果同时启用IPv4和IPv6 则需要考虑更多的问题。目前只做纯IPv4/IPv6
针对#2407 的一种解决方案 
增加了`isIPv6Enabled` 标记，默认仍为关闭保持原样。
当手动修改配置文件`gui-config.json`后 增加或者修改 
``` isIPv6Enabled = true```
后，将启用纯IPv6模式，原IPv4 监听的 1080 [tcp/udp] `ss_privoxy`随机 都将默认从IPv4切换到IPv6
`0.0.0.0`->`[::]`,`127.0.0.1`->`[::1]` 
切换后如图【允许其他设备接入】
关闭【允许其他设备接入】
存在的瑕疵：
目前有一个参数 `LocalHost` 会被写入到配置文件，但我不希望写入，这个需要解决。
代码中 `LocalHost=>GetLocalHost()` 是希望其他地方可以像`localPort`参数一样引用这个动态的`localHost` ，但对c#不熟悉所以不知道如何让 json 把这个 参数当成普通参数不进行json序列化。
=> 纯IPv6本地监听支持

shadowsocks-csharp/Util/Util.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/shadowsocks-csharp.csproj
---
Support Windows 10 1903 light theme. (Menu icon color adaptive, previous version icons are indistinguishable at light theme)
Icon more beautiful. (use alpha replace 128 gray)
支持 Windows10 1903 的“亮”主题色。（菜单图标颜色自适应，之前版本图标会在亮色主题下难以看见）
图标更加美观。（使用Alpha通道替换128灰色）
=> Support Windows 10 1903 Light Theme

shadowsocks-csharp/View/ConfigForm.cs
---
修复删除时事件触发导致，错误的删除。
修改服务器列表位置调整逻辑，与 `4.16` 版本保持一致。
=> Fix #2458 Unexpected delete server behavior

shadowsocks-csharp/View/ConfigForm.cs
---
完善用户操作习惯，在切换配置时启用应用按钮，而不是配置内容修改时。
#2457
=> Switch configuration enable button

shadowsocks-csharp/View/ConfigForm.cs
Fixed an invalid index that was unexpectedly caused when the configuration was abandoned, resulting in an list box index exception.
---
see details: #2542
=> [fixes #2542] Fix accidental index invalidation

shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs, shadowsocks-csharp/Controller/Strategy/StatisticsStrategy.cs
---
fix #1970, and also find some other thread-safe problem in statistics feature, all tagged.
=> FIX: some crash about thread-safe in statistics

shadowsocks-csharp/View/MenuViewController.cs
Fixes https://github.com/shadowsocks/shadowsocks-windows/issues/2657
Support Windows 10 1903 Light Theme
But Fix Support Windows 10 1903 Dark Theme
---
=> BugFix #2657 win10 1903 黑色主题下， trayIcon 会消失的问题；

shadowsocks-csharp/Controller/Strategy/StatisticsStrategy.cs
---
Use already calculated id variable instead of server.Identifier().
=> Use id instead of calculating server.Identifier()

shadowsocks-csharp/Model/Server.cs
---
#2668 , update default method to reflect change of protocol and server.
=> change default method to chacha20-ietf-poly1305

shadowsocks-csharp/Controller/Service/PACServer.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Controller/System/SystemProxy.cs
---
在PAC URL中改用MD5哈希替代时间戳，仅在PAC内容变化时产生新的URL参数。
=> Use MD5 hash instead of timestamp for PAC URL

shadowsocks-csharp/Controller/Service/Sip003Plugin.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/View/MenuViewController.cs, test/Sip003PluginTest.cs
---
This is a simple improvement that allows viewing the plugin output window instead of always hiding it. It can be very useful to debug plugin issues instead of being forced to duplicate the config and run the plugin standalone just to see its output.
=> Implement "Show Plugin Output" checkbox.

shadowsocks-csharp/Controller/Service/GfwListUpdater.cs, shadowsocks-csharp/Model/Configuration.cs
---
User is able use a custom "GFWList" which defined in config file.
Config file only. No UI.
=> Support custom GFWListUrl defined in config file

shadowsocks-csharp/Controller/I18N.cs, shadowsocks-csharp/Data/i18n.csv, shadowsocks-csharp/View/MenuViewController.cs
=> Fix #2740, write i18n.csv on demand

shadowsocks-csharp/View/MenuViewController.cs
Fix #2782
---
When there is a "New Server" in the server list, the context menu from tray icon will have wrong selected server in the server list.
=> Bug fix: wrong server in tray menu as selected server when there has an invalid server in the list

shadowsocks-csharp/Data/i18n.csv, shadowsocks-csharp/View/ConfigForm.Designer.cs, shadowsocks-csharp/View/ConfigForm.cs
---
Close #2715, some heavy modify in ConfigForm.cs in order to show deprecated warning in EncryptionSelect
=> deprecate unsafe encryption method

shadowsocks-csharp/View/ConfigForm.cs
https://github.com/shadowsocks/shadowsocks-org/issues/154
---
Mark all stream cipher deprecated. Planning to remove them in V5.
https://github.com/shadowsocks/shadowsocks-org/issues/154
=> deprecate all stream cipher

shadowsocks-csharp/Model/NlogConfig.cs
---
Avoid application crash when not having file permissions to setup default NLog.config. See also #2841
=> NLogConfig - TouchAndApplyNLogConfig with Exception handler

shadowsocks-csharp/Controller/Service/TCPRelay.cs
Fixes https://github.com/shadowsocks/shadowsocks-windows/issues/2857
=> Update TCPHandler.lastActivity upon successful send of bytes.

shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs
---
Using event to update statistic data.
=> Decouple statistic and TCPRelay

shadowsocks-csharp/Model/Configuration.cs
=> Fix nLogConfig NRE

shadowsocks-csharp/Controller/Service/GeositeUpdater.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/packages.config, shadowsocks-csharp/shadowsocks-csharp.csproj
---
- Compared to 2c15276: changed `socketsHttpHandler` to `HttpClientHandler` due to legacy .NET Framework
- Use `System.Net.Http.HttpClient` for `GeositeUpdater`
- New update check mechanism: first download checksum and compare, only download GeoSite DB on different checksum
- Verifiy downloaded GeoSite DB by comparing sha256sum before committing the change
=> 🔙 Backport 2c15276 from v5/master to master

shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs, shadowsocks-csharp/Controller/Service/TCPRelay.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Controller/Strategy/HighAvailabilityStrategy.cs, shadowsocks-csharp/Controller/Strategy/StatisticsStrategy.cs, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/Model/Server.cs, shadowsocks-csharp/View/ConfigForm.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/View/QRCodeForm.cs, test/UrlTest.cs
---
Always generate SIP002 URL. User can generate legacy URL via hidden flag in config.
Close #2774
=> Always sip002

shadowsocks-csharp/Model/Server.cs, test/UrlTest.cs
---
Current implementation of SIP002 URI Scheme parser produces wrong output for a URI with spaces in its `fragment` section.
Given URI `ss://YmYtY2ZiOnRlc3Q@192.168.100.1:8888/?plugin=obfs-local%3bobfs%3dhttp%3bobfs-host%3dgoogle.com#example-server+1`, a `Server` with remark `example-server 1` is created.
Given URI `ss://YmYtY2ZiOnRlc3Q@192.168.100.1:8888/?plugin=obfs-local%3bobfs%3dhttp%3bobfs-host%3dgoogle.com#example-server+1`, a `Server` with remark `example-server+1` is created.
Current behavior was also observed in other SIP002 …
=> Fix improperly parsed remark section

shadowsocks-csharp/Controller/Service/OnlineConfigResolver.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Data/i18n.csv, shadowsocks-csharp/Model/Configuration.cs, shadowsocks-csharp/Model/Server.cs, shadowsocks-csharp/Program.cs, shadowsocks-csharp/View/ConfigForm.Designer.cs, shadowsocks-csharp/View/ConfigForm.cs, shadowsocks-csharp/View/ConfigForm.resx, shadowsocks-csharp/View/HotkeySettingsForm.designer.cs, shadowsocks-csharp/View/MenuViewController.cs, shadowsocks-csharp/View/OnlineConfigForm.Designer.cs, shadowsocks-csharp/View/OnlineConfigForm.cs, shadowsocks-csharp/View/OnlineConfigForm.resx, shadowsocks-csharp/shadowsocks-csharp.csproj
---
Close #1703
Close #2939
Close #2928
Finally, here we are......
Some glitch is expected...
=> Sip008 initial support

shadowsocks-csharp/Controller/Service/GeositeUpdater.cs
---
- PAC proxied list now only contains domain names from geolocation-!cn without a `cn` attribute
- Closes #2971.
- Closes #2974.
- Closes #2981.
=> 📃 Exclude @cn from PAC proxied list

shadowsocks-csharp/Controller/Service/GeositeUpdater.cs, shadowsocks-csharp/Controller/Service/OnlineConfigResolver.cs, shadowsocks-csharp/Controller/ShadowsocksController.cs, shadowsocks-csharp/Model/Configuration.cs
Signed-off-by: Beta Soft <betaxab@gmail.com>
---
User-Agent should be added to `httpClient` to get online configuration.
Use the shadowsocks-windows owns name  `ShadowsocksWindows/{UpdateChecker.Version}` instand of Web Browser default UA should be better, help online configuration API determine the client …
=> OnlineConfigResolver: add User-Agent

shadowsocks-csharp/Data/abp.js
---
- Could match domains with similar patterns. But that's all we can do for now.
- No active developers use PAC mode. We are looking to deprecate PAC in favor of routing solutions.
- Closes #3002.
=> 🎃 PAC: workaround to exempt private IP ranges in whitelist mode

shadowsocks-csharp/Controller/System/AutoStartup.cs
=> remove duplicate startup entries
