shadowsocks/shadowsocks-windows

- shadowsocks-csharp/Controller/Local.cs
- shadowsocks-csharp/Controller/Logging.cs
- shadowsocks-csharp/Controller/UpdateChecker.cs
Simple implementation that adds a time stamp prefix to each log line.
> Logging timestamp

- shadowsocks-csharp/Model/Server.cs
关掉 https://github.com/shadowsocks/shadowsocks-csharp/issues/131
我就是爱用中文，哼~
> 解决 QRcode 地址解析中密码可能带@符号、服务器名可能带冒号的问题

- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/View/QRCodeForm.Designer.cs
- shadowsocks-csharp/View/QRCodeForm.cs
- shadowsocks-csharp/View/QRCodeForm.resx
To add multiple servers in android phone, now it is no need to chose server one by one and generate QRCode for each. Just need to select the server listed in right.
> Added list of servers in QRCode generate window to select.

- README.md
> Add gfwlist links

- shadowsocks-csharp/Controller/Service/UpdateChecker.cs
- shadowsocks-csharp/Data/cn.txt
- shadowsocks-csharp/View/LogForm.Designer.cs
- shadowsocks-csharp/View/LogForm.cs
improved `log viewer`:
1. add `clean log` feature
2. add `change font` feature
3. add `wrap text` feature
4. add `top most` feature
5. rename variables name to meaningful one. such as `menuItem2` -> `OpenLocationMenuItem`
> improved `log viewer` windows

- shadowsocks-csharp/Controller/Service/GfwListUpdater.cs
https://code.google.com/p/autoproxy-gfwlist/
The old one will no longer update.
> Update GFWList URL

- shadowsocks-csharp/View/ConfigForm.cs
添加了服务器信息后，逐个删除服务器信息，在添加新的信息时会报 System.ArgumentOutOfRangeException
> fix ArgumentOutOfRangeException

- .gitignore
- nuget.config
- shadowsocks-csharp/Controller/Service/TCPRelay.cs
- shadowsocks-csharp/Controller/Service/UDPRelay.cs
- shadowsocks-csharp/Program.cs
not open log file in debug mode, cause error when open log.
> Fix error in open log file in debug mode.

- README.md
- shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs
- shadowsocks-csharp/Controller/Service/UpdateChecker.cs
- shadowsocks-csharp/View/MenuViewController.cs
- shadowsocks-csharp/View/StatisticsStrategyConfigurationForm.cs
Fix crash when serverIP is an IPv6 address
> Fix #399 for branch 'with_online_config'

- shadowsocks-csharp/Controller/FileManager.cs
- shadowsocks-csharp/Controller/Logging.cs
- shadowsocks-csharp/Controller/Service/PACServer.cs
- shadowsocks-csharp/Controller/Service/UpdateChecker.cs
- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Model/Configuration.cs
- shadowsocks-csharp/Model/Server.cs
- shadowsocks-csharp/View/MenuViewController.cs
- shadowsocks-csharp/app.config
- shadowsocks-csharp/packages.config
- shadowsocks-csharp/shadowsocks-csharp.csproj
featured:
1. daily rolling log file
2. save bandwidth in file config.json
---
BTW, can you guys bump up v2.5.9 ;-)
> added 2 features

- shadowsocks-csharp/Data/cn.txt
add statistics config translation
> add statistics config translation

- shadowsocks-csharp/Controller/Service/GfwListUpdater.cs
- shadowsocks-csharp/Controller/ShadowsocksController.cs
> more unnecessary optimize

- shadowsocks-csharp/View/MenuViewController.cs
> Feature #490 We can get proxy state according to tray icon color

- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Model/Server.cs
This commit implements the new ss protocol proposed here:
https://github.com/shadowsocks/shadowsocks-org/issues/16
Also removes a TODO in Server.cs. You are welcome.
> Support one-time authentication in ss urls for sharing

- shadowsocks-csharp/View/ConfigForm.Designer.cs
changed password mask from star mark `*` to bullet marker `∙`
> fixed password mask

- shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs
- shadowsocks-csharp/Controller/Service/PolipoRunner.cs
- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Data/cn.txt
- shadowsocks-csharp/Program.cs
- shadowsocks-csharp/packages.config
- shadowsocks-csharp/shadowsocks-csharp.csproj
- test/packages.config
- test/test.csproj
Squashed commit of the following:
commit e280c2385c234f68e3b653dbd9efc26ed9df002f
Merge: 579039f 87aa9eb
Author: Gang Zhuo <gang.zhuo@gmail.com>
Date:   Wed Mar 16 04:02:27 2016 -0400
Merge remote-tracking branch 'origin/master'
commit 579039fe40d2ac66b97fd9cbfe6bda695d4e92ec
Author: Gang Zhuo <gang.zhuo@gmail.com>
Date:   Fri Mar 4 21:45:23 2016 +0800
log unhandle exception
commit 8d863f1d5f484bf636a0780f5e69d944b1810ae2
Author: Gang Zhuo <gang.zhuo@gmail.com>
Date:   Fri Mar 4 21:44:54 2016 +0800
fix Availability Statistics
commit b3ce1c698a7518e76f521c411ca0d4240fc2f34a
Author: Gang Zhuo <gang.zhuo@gmail.com>
Date:   Fri Mar 4 21:07:54 2016 +0800
tiny refactor
commit 0f7d39e27ef524bfa2d75034066bb074c91f91e6
Merge: bd7078a b01aced
Author: Gang Zhuo <gang.zhuo@gmail.com>
Date:   Fri Mar …
> Merge fixes from @GangZhuo, close #478

- shadowsocks-csharp/Data/cn.txt
- shadowsocks-csharp/View/LogForm.cs
> apply I18N to traffic chart legend

- shadowsocks-csharp/Model/Server.cs
- shadowsocks-csharp/View/LogForm.cs
Try to fix https://github.com/shadowsocks/shadowsocks-windows/issues/465
> Minor bugfixes

- shadowsocks-csharp/View/LogForm.cs
- shadowsocks-csharp/View/MenuViewController.cs
fix bandwidthScale of the LogForm
not save RECT if LogForm is minimized
activate ConfigForm & ProxyForm & LogForm
> fix bandwidthScale of the LogForm

- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Util/Util.cs
- shadowsocks-csharp/View/LogForm.Designer.cs
- shadowsocks-csharp/View/LogForm.cs
- remove invoke
- force to set AxisY.Maximum not zero
- format LogForm.cs
> new traffic chart style

- shadowsocks-csharp/Encryption/SodiumEncryptor.cs
revert change from 3bc77d212a711d9482a864b49eae59203a79340b
> remove lock in SodiumEncryptor

- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Encryption/IVEncryptor.cs
- shadowsocks-csharp/Encryption/RNG.cs
- shadowsocks-csharp/shadowsocks-csharp.csproj
- test/UnitTest.cs
- Create instance once, bind it to ShadowsocksController
> Refine RNG usage

- shadowsocks-csharp/Program.cs
> Detach static event handler before exiting

- shadowsocks-csharp/Data/cn.txt
- shadowsocks-csharp/Data/zh_tw.txt
- shadowsocks-csharp/Model/HotKeyConfig.cs
- shadowsocks-csharp/View/HotkeySettingsForm.cs
- shadowsocks-csharp/View/HotkeySettingsForm.designer.cs
- shadowsocks-csharp/View/HotkeySettingsForm.resx
Merge 'Switch to PAC' and 'Switch to Global'
> hotkey: Refine system proxy mode switching logic

- shadowsocks-csharp/Model/Server.cs
> Add optional tag support for ss url

- shadowsocks-csharp/Controller/ShadowsocksController.cs
- shadowsocks-csharp/Model/Server.cs
- shadowsocks-csharp/shadowsocks-csharp.csproj
> Use UTF-8 encoding for optional tag in ss url

- shadowsocks-csharp/Controller/Service/PrivoxyRunner.cs
Let TCP stack find a free port for us
> Fix privoxy listening port conflict

- shadowsocks-csharp/View/MenuViewController.cs
> not set alpha of the icon

- shadowsocks-csharp/Controller/Service/TCPRelay.cs
> Send first chunk with Socks5 header

- shadowsocks-csharp/Data/ja.txt
- shadowsocks-csharp/Data/zh_CN.txt
- shadowsocks-csharp/Data/zh_TW.txt
- shadowsocks-csharp/View/ConfigForm.Designer.cs
- shadowsocks-csharp/View/ConfigForm.cs
- shadowsocks-csharp/View/ConfigForm.resx
- shadowsocks-csharp/shadowsocks-csharp.csproj
>  Add option to show password

- shadowsocks-csharp/Controller/Service/Listener.cs
This might fix 500 Privoxy Internal Error: no-server-data
> Close connection if received zero bytes

- shadowsocks-csharp/Controller/Service/GfwListUpdater.cs
Fix: #1468
Enhance: 46d40fec678c7ab3c1cd6743e675aa13b6d6af77
上面那个提交貌似只改了由于 user-rule.txt 文件更改导致的 PAC 文件更新，而没有改主动更新 PAC 文件的部分。
> Put user rules at the begin of the PAC file.

- shadowsocks-csharp/Controller/ShadowsocksController.cs
> Server address should not be encoded

- shadowsocks-csharp/Data/zh_CN.txt
- shadowsocks-csharp/Model/Server.cs
- shadowsocks-csharp/View/ConfigForm.cs
修复ConfigForm不安全代码。链接分隔符支持空格。
Fix #1961
> 修复ConfigForm不安全代码。链接分隔符支持空格。

- test/ProcessEnvironment.cs
- test/UnitTest.cs
- test/test.csproj
---
Unit test from #1974 . Consider that most programmer open at least one cmd during working, currently use `ftp.exe` as fake plugin.
考虑到程序员基本上都要开一个cmd，却没人开ftp，暂时使用ftp作为假插件。
> Unit test for plugin launch

- shadowsocks-csharp/View/StatisticsStrategyConfigurationForm.cs
> 补上Statistics界面的图标

- shadowsocks-csharp/Model/SysproxyConfig.cs
- shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs
…omment-445434934
---
Fix for null reference error of bypass list merge feature in v4.1.3.
> Fix #2100 NullReference

- shadowsocks-csharp/Controller/ShadowsocksController.cs
> Update the system proxy when user-rule.txt changed

- shadowsocks-csharp/Controller/System/AutoStartup.cs
- shadowsocks-csharp/Program.cs
---
在系统重启或更新后自启。在我的机器上可用，可能需要更多测试。
Restart program after system reboot/update. Works on my machine, may need more test.
> Register restart after system reboot, #2154

- shadowsocks-csharp/Encryption/Stream/StreamMbedTLSEncryptor.cs
- shadowsocks-csharp/Encryption/Stream/StreamOpenSSLEncryptor.cs
---
Removed unused array allocations in order to decrease memory traffic.
> Removed unused array allocations

- shadowsocks-csharp/Data/ja.txt
- shadowsocks-csharp/Data/zh_CN.txt
- shadowsocks-csharp/Data/zh_TW.txt
- shadowsocks-csharp/View/MenuViewController.cs
- [ x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [ x] Compiled the code with Visual Studio
- [ x] Improvement
---
This is kind of implement for [issue 2266](https://github.com/shadowsocks/shadowsocks-windows/issues/2266), but a bit different.
*    Enable system proxy
*    Mode
*  PAC
*  Global
*    Proxy
* Disable
* PAC
* Global
...
System proxy config will be switched between these three status.
> Enhance context menu  for System proxy and it's mode.

- shadowsocks-csharp/Data/ja.txt
- shadowsocks-csharp/Data/zh_CN.txt
- shadowsocks-csharp/Data/zh_TW.txt
- shadowsocks-csharp/Properties/Resources.Designer.cs
- shadowsocks-csharp/View/ConfigForm.Designer.cs
- shadowsocks-csharp/View/ConfigForm.cs
---
Implementation for issue [2180](https://github.com/shadowsocks/shadowsocks-windows/issues/2180)
> Add "Apply" button to Editor Servers form 

- shadowsocks-csharp/Model/Configuration.cs
- shadowsocks-csharp/View/ConfigForm.cs
---
Fixed issue described in #2371 and checked for potential errors.
😄
> fixed issue #2371

- .github/issue_template.md
> issue_template: ask users to delete the instruction text

- shadowsocks-csharp/Program.cs
Fix https://github.com/shadowsocks/shadowsocks-windows/issues/2471
混个contributor _(:з」∠) 如果位置不合适就告诉我来改
> Fix .NET 4.7.2 on Win7 TLS compatibility

- shadowsocks-csharp/Controller/Service/GfwListUpdater.cs
Update the PAC file using the proxy channel only when proxy mode is enabled.
---
Update the PAC file using the proxy channel only when proxy mode is enabled. #2525 
> Modify PAC request behavior

- appveyor.yml
- appveyor.yml.obsolete
- appveyor.yml.sample
- nuget.config
- shadowsocks-csharp/FodyWeavers.xsd
- shadowsocks-csharp/packages.config
- shadowsocks-csharp/shadowsocks-csharp.csproj
- test/ShadowsocksTest.csproj
- test/packages.config
> Rewrite the Appveyor build pipeline

- shadowsocks-csharp/Data/zh_CN.txt
- shadowsocks-csharp/View/StatisticsStrategyConfigurationForm.Designer.cs
- shadowsocks-csharp/View/StatisticsStrategyConfigurationForm.cs
---
#2583 with I18N enabled in code
> Translate statistics config

- CONTRIBUTING.md
> Update CONTRIBUTING.md to reflect current state

- shadowsocks-csharp/Data/i18n.csv
- shadowsocks-csharp/View/ConfigForm.cs
---
When a cipher not exist (user migrate from a too old version), show a warning message instead of crash.
> show message when cipher not exist

- shadowsocks-csharp/View/ConfigForm.cs
> Fix ConfigForm wrong move data

- shadowsocks-csharp/Data/i18n.csv
---
The translation file format of the master branch and 4.1.9.2 release is different, please let me know if you need 4.1.9.2 translation created with `create translation template` button.
> Add Korean (ko) translation

- shadowsocks-csharp/Data/i18n.csv
---
Add French translation (first version) to i18n.csv
> add French translation

- shadowsocks-csharp/Data/i18n.csv
---
Added Missing Lines, Fixed Grammar and Typo and Corrected Wrong Translation. Based By https://github.com/shadowsocks/shadowsocks-windows/pull/2835
> Updated Korean Language

- appveyor.yml
---
- New artifact: single .exe for better portability.
- Cleanup: removed unnecessary copies.
> 📦 More artifacts: Package into a self-contained single-file executable for better portability.

- shadowsocks-csharp/Controller/Service/UDPListener.cs
- shadowsocks-csharp/Controller/Service/UDPRelay.cs
- shadowsocks-csharp/Encryption/Stream/StreamPlainNativeEncryptor.cs
---
Make v5 UDP proxy actually works. And refactor with Task based async API to make things clear.
> v5 udp fix

- shadowsocks-csharp/Encryption/CryptoUtils.cs
---
1. Code optimization for "SodiumIncrement" method.
2. No longer need "byte[]" version for compatibility, for it's return void.
> Code optimization for SodiumIncrement

- shadowsocks-csharp/Encryption/CryptoUtils.cs
---
1. .NET Core 下 FIPS 兼容
2. 不需要第三方库
3. 开销小
4. 性能更佳
5. 线程安全
<details>
<summary>Benchmark</summary>
Source: https://gist.github.com/HMBSbige/fa41c58b8dc7713a15d079227fefeb43
</details>
> Optimization for MD5

- shadowsocks-csharp/Controller/Service/GeositeUpdater.cs
- shadowsocks-csharp/Model/Configuration.cs
> 🧂 Add option for custom sha256sum URL of custom geosite source

- Shadowsocks.Interop/V2Ray/FakeDnsObject.cs
- Shadowsocks.Interop/V2Ray/RoutingObject.cs
---
Just make settings comply with V2Ray config.
> Chore: comply with V2Ray config

- CHANGES
- appveyor.yml
- shadowsocks-csharp/Controller/Service/UpdateChecker.cs
- shadowsocks-csharp/Encryption/EncryptorFactory.cs
- shadowsocks-csharp/Encryption/Stream/PlainEncryptor.cs
- shadowsocks-csharp/View/ConfigForm.cs
- shadowsocks-csharp/shadowsocks-csharp.csproj
Also bump the version to 4.4.1.0
> Add the plain/none cipher
